dist: trusty
sudo: false
group: beta

cache:
  directories:
    - $HOME/.yarn-cache

env:
  - SIDE=server
  - SIDE=app

before_install:
  - nvm install 7
  - npm install -g yarn

install:
  - yarn install

script:
  - if [[ "$SIDE" == "server" ]]; then npm run server-lint; fi
  - if [[ "$SIDE" == "server" ]]; then npm run server-test; fi
  - if [[ "$SIDE" == "server" ]]; then npm run server-build; fi
  - if [[ "$SIDE" == "app" ]]; then npm run app-build; fi
