dist: trusty
sudo: false
group: beta

cache:
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install 7
  - npm install -g yarn

install:
  - yarn install

script:
  - npm run server-lint
  - npm run server-test
  - npm run server-build
  - npm run app-build
