# Password securing your Homie Dashboard
password = "abcd"

# Enable bindings
[bindings]

  [bindings.aqara]
    enabled = true

    [bindings.aqara.gateway]
      ip = '192.168.6.17'
      key = '000000000000'
  [bindings.yeelight]
    enabled = true

# Credentials to your MQTT broker
[mqtt]
host = "127.0.0.1"
port = 1883

# Data needed for the configuration of homie-esp8266 devices
[homie-esp8266]

  [homie-esp8266.wifi]
  ssid = "SSID"
  password = "password"

  [homie-esp8266.mqtt]
  host = "192.168.1.10"
  port = 1883
